services:
  url-shortner:
    container_name: url-shortner
    build:
      context: ./url-shortner
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./url-shortner/.env
    depends_on:
      - db

  notification-service:
    container_name: notification-service
    build:
      context: ./notificaiton-service
      dockerfile: docker/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./notificaiton-service/.env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortner
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./url-shortner/migrations:/docker-entrypoint-initdb.d

  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  db_data:
