services:
  url-shortner:
    container_name: url-shortner
    build:
      context: ./url-shortner
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./url-shortner/.env
    depends_on:
      db:
        condition: service_healthy

  notification-service:
    container_name: notification-service
    build:
      context: ./notification-service
      dockerfile: docker/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./notification-service/.env
    depends_on:
      notification-db:
        condition: service_started

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortner
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./url-shortner/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  notification-db:
    image: postgres:15-alpine
    container_name: notification-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notification
    ports:
      - "5434:5432"
    volumes:
      - notification_db_data:/var/lib/postgresql/data
      - ./notification-service/migrations:/docker-entrypoint-initdb.d

  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "6399:6379"

  db_test:
    image: postgres:15-alpine
    container_name: db_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortner_test
    ports:
      - "5433:5432"
    volumes:
      - ./url-shortner/migrations:/docker-entrypoint-initdb.d

  notification-db-test:
    image: postgres:15-alpine
    container_name: notification-db-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notification_test
    ports:
      - "5435:5432"
    volumes:
      - ./notification-service/migrations:/docker-entrypoint-initdb.d

volumes:
  db_data:
  notification_db_data:
  db_test_data:
